version: '3.8'

services:
  # Сервис авторизации
  auth-service:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - redis
    networks:
      - auth-network
    restart: always

  # Сервис Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - auth-network
    restart: always

  # Сервис Postgres
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - auth-network
    restart: always


# Сетевые настройки
networks:
  auth-network:
    driver: bridge
