version: '3.8'

services:
  # Сервис авторизации
  auth-service:
    build:
      context: ..                         # Указываем контекст сборки на родительскую директорию (папка auth-service)
      dockerfile: deployments/Dockerfile   # Указываем путь к Dockerfile в директории deployments
    ports:
      - "8080:8080"                       # Проброс порта 8080 для общения с сервисом
    env_file:
      - ../.env
    depends_on:
      - redis                             # Зависимость от контейнера Redis
    networks:
      - auth-network
    restart: always                       # Автоматический перезапуск контейнера в случае сбоев

  # Сервис Redis
  redis:
    image: redis:alpine                  # Используем официальный образ Redis
    container_name: redis
    ports:
      - "6379:6379"                      # Проброс порта Redis
    networks:
      - auth-network
    restart: always                      # Автоматический перезапуск контейнера в случае сбоев

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - auth-network
    restart: always



# Сетевые настройки
networks:
  auth-network:
    driver: bridge
